### PR TITLE
[ENH] Add docker build and test workflow WIP

### LINKED ISSUE #2: [DEV] - Add tests to the images
A CI/CD workflow should test the images after the build and before pushing.

## Tasks

- [ ] Identify and add common tests (for all images)
- [ ] Identify and add any image specific tests
- [ ] Add step to GH action workflow

### PR DESCRIPTION
**Pull request by viniciusdc**
closes #2 

## What does this implement/fix?

Note that these jobs only run for the changed files to avoid executing unnecessary actions

This pull request adds a new test workflow for new PR, where we will be able to:
- Test the current conda environments before building it inside the docker images. this will help identify any errors before attempting the build (which is faster)
- Lints the Docker code syntax for each image
- Cache environment builds and Docker layers to avoid fresh builds on each change
- Add in docker Pytest specialized workflow for each image (in progress) 

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [x] Did you add new tests? (wip)

## Documentation

I will add some docs regarding this workflow once I run some preliminary tests. 

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### Any other comments?
This is a workflow diagram of this new pipeline (which needs to be updated):

Blank diagram (1)

### CODE REVIEW

**Comment by viniciusdc** [comment]
I will squash the tests and trivial commits, later on, to avoid unnecessarily commit history

**Comment by viniciusdc** [comment]
Also, the main reason behind adopting the Local registry during image building was based on this preliminary [time comparison research](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei).

**Comment by pavithraes** [comment]
@viniciusdc Shall we consider closing this PR? We can always re-open at a later date when we want to pick it back up. :)

**Comment by trallard** [comment]
yes let's close for now and we can pick this up later

**Pull request closed without merging**
