### PR TITLE
Switch default env to global

### PR DESCRIPTION
**Pull request by iameskild**
## Reference Issues or PRs

Related to https://github.com/Quansight/qhub/issues/1349

## What does this implement/fix?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### CODE REVIEW

**Comment by trallard** [comment]
ok this seems to be a duplicate of #22 - same question anything needed here?

**Comment by iameskild** [comment]
Hey @trallard I opened this as a follow up to this https://github.com/Quansight/qhub/pull/1357 and this is still a WIP. @viniciusdc and I will need to test this change.

**Comment by viniciusdc** [comment]
@iameskild I know I originally suggested this change, but right now, we have default as an environment in the jupytelab user pod ecosystem that seems to be agnostic of the namespaces; I think we can keep that as it is now and drop this change what do you think?

**Comment by iameskild** [comment]
@viniciusdc that's fine with me 👍

**Pull request closed without merging**
