### PR TITLE
[ENH] Add xvfb to Jupyterlab env

### PR DESCRIPTION
**Pull request by viniciusdc**
## Reference Issues or PRs

This is an original request originally made in https://github.com/Quansight/qhub/pull/1348, with the images now migrated those changes should me included in here.

## What does this implement/fix?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### Any other comments?

I don't see any problem adding this to our images, as it's required for pyvista to work properly. Though we must discuss proper ways to update/add libs to these images in the future.

### CODE REVIEW

**Review by iameskild — APPROVED** [review]
Thanks for following up on this @viniciusdc :)

**Comment by rsignell-usgs** [comment]
After this is approved, what would I need to do to implement this on the ESIP qhub deployment?

**Comment by iameskild** [comment]
@rsignell-usgs we recently moved away from pushing our images to Dockerhub in favor of pushing to quay.io. This means that once this is merged, you can replace the images under `default_images` like this:

```
default_images:
  jupyterhub: quay.io/nebari/nebari-jupyterhub:sha-xxx
  jupyterlab: quay.io/nebari/nebari-jupyterlab:sha-xxx
  dask_worker: quay.io/nebari/nebari-dask-worker:sha-xxx
```

The `sha-xxx` can be replaced with the version number or `main`.

**Comment by rsignell-usgs** [comment]
Awesome!  Thanks @iameskild !

**Pull request merged**
