### PR TITLE
Add git-lfs to jupyterlab base image

### LINKED ISSUE #88: [ENH] - Add git-lfs to base image
### Feature description

I propose that git-lfs should be added to the base image to enable its usage by all users. 

There is an apt-get workflow to download it, but since apt is unavailable to end users, they need to install it with `wget` directly from the repository. 

I'm not a Dev Ops person maintaining our nebari deployment so I did't know which of the available files would work on the deployment. Here are the available files to wget from the repo:

image

** Workaround ** 

This is the current workflow to get git-lfs on Nebari:

```
wget https://github.com/git-lfs/git-lfs/releases/download/v3.4.0/git-lfs-linux-amd64-v3.4.0.tar.gz

tar -xvf git-lfs-linux-amd64-v3.4.0.tar.gz

./git-lfs-3.4.0/git-lfs --help

```

### Value and/or benefit

Life gets easier for end users. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iameskild**
## Reference Issues or PRs

Closes #88 

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by aktech** [comment]
Any reason why we shouldn't get this from conda: https://anaconda.org/conda-forge/git-lfs/

**Comment by iameskild** [comment]
@aktech I added `git-lfs` to the environment.yaml so it should be pulling from conda-forge right?

**Comment by aktech** [comment]
Ah, I misread that as apt packages list

**Review by aktech — APPROVED** [review]
Looks great!

**Pull request merged**
